### ISSUE TITLE
class decorators in ES6 not working due to direct constructor call

### ISSUE THREAD

**Issue by fuzing** [asvetliakov/Huject#1]
First - thanks for working on this project.

I've identified an issue with ES6 in that class constructors cannot be called directly without 'new'.  Therefore, many decorator implementations fail with the following error (or similar, depending on environment):

TypeError: Class constructors cannot be invoked without 'new'

The problem is due to the fact that for 'class decorators' this library (and most others) are returning a new constructor that 'calls' the old constructor in a manner similar to this:

  oldConstructor.apply(this, args);

With ES5 this works fine (i.e. classes are simply functions), but in ES6 this fails with the error above.

I haven't figured out a solution to the problem, and thought I'd raise it for your implementation.

Cheers,

Peter B.

**Comment by asvetliakov** [comment]
Yes, that is the problem. Thanks for pointing to this. Will be working on fix on next days.

**Comment by fuzing** [comment]
Thanks a lot - I've looked around for a solution and this one may pose a big problem...... I don't see an easy solution (I'll keep looking / working on it though).

Do you want me to go ahead and close this out, or wait to see what you come up with....?

Be well,

PB

**Comment by fuzing** [comment]
FYI...... I just discovered an npm called 'to-factory' that may be the ticket!
https://github.com/timoxley/to-factory

**Comment by fuzing** [comment]
FYI - a quick and dirty test of the above NPM works like a charm........ i.e. (for node/V8)......

let toFactory = require('to-factory')
toFactory(oldConstructor).apply(this, args);

However this is naive, and does not take into account the side-effects of converting between es6 class and simple function (and vice-versa), so the final implementation of the class decorator method should test if oldConstructor is a class (then make sure a class is returned as the new constructor),   else make sure a function is returned as the new constructor.

Hope this helps.

Cheers,

Peter B.

**Comment by asvetliakov** [comment]
Quick look:
I'm using this

``` typescript
        let newConstructor = function () {
            constructor.apply(this, constructorArguments);
        };
        newConstructor.prototype = constructor.prototype;
       ...
```

only for passing constructor arguments or injected dependencies. I can avoid it's overriding by just resolving arguments in top-level function and passing them to the new(). Shouldn't be hard.

**Comment by asvetliakov** [comment]
Please try 1.3.4 version, if it works for you close the issue. Thanks

**Comment by fuzing** [comment]
Will do - thank you!

**Comment by fuzing** [comment]
Yes and no.........

The class decorator seems to have been fixed and is now working correctly.....  and hence this seems to work (based on service location using string):
https://gist.github.com/fuzing/19f7bdeaef684ef4a01d

However, registering a class/interface and using that method throws exception with the 'TypeError: Class constructors cannot be invoked without 'new''   error........
as in this......
https://gist.github.com/fuzing/cc61e57f825b2eb02780

I haven't looked at the huject code to figure out what's going on, but appears to be an issue with the way that dependencies are instantiated(!?)

Thanks.

**Comment by asvetliakov** [comment]
``` typescript
constructor(@ConstructorInject(Logger) logger : LoggerInterface) {
```

That will not work, @ConstructorInject decorator inside constructor arguments could be used only with literal and/or FactoryMethod.

**Comment by asvetliakov** [comment]
Also this:

``` typescript
//
//
//  NOTE: Alexey..... this variant (interface => implementation) also fails
//container.register(Logger, Logger, ['some parameter']).as(FactoryMethod.SINGLETON);
//
//
```

If you need to bind interface -> implementation you need to use class (or abstract class) instead of interface (see readme). To just register constructor arguments for class you need to use this form:

``` typescript
container.register(Logger, ['some parameter']).as(FactoryMethod.SINGLETON);
```

**Comment by fuzing** [comment]
Thanks Alexey......   I was aware of the differences - it was just a quick and dirty implementation to show you how it was failing.   When I referred to 'interface' in the code, you'll note I was not actually using an interface (which, under Typescript, emits no code), but was using the implementation/class (twice).

Given the @ConstructorInject decorator inside constructor arguments limitation, then I think I can close this out.......   The class decorator is working.

Interestingly, I think the typescript team is discussing an option whereby 'interface names' might be emitted as metadata under certain conditions........ which will be an awesome addition in that it will allow DI/IOC frameworks to locate/inject by interface.   Can't wait.

Hey - thanks for your help!

Peter B.

**Comment by asvetliakov** [comment]
>Interestingly, I think the typescript team is discussing an option whereby 'interface names' might be emitted as metadata under certain conditions........ which will be an awesome addition in that it will allow DI/IOC frameworks to locate/inject by interface. Can't wait.
No, they aren't. They considered to implement the full type serialization with JSON format or so few months ago (in summer), but decided to not do it. Also this can break existing code which assuming that interfaces are not real objects. The best way is to introduce new language semantics for interfaces which exist in realtime or make runtime checks for abstract classes and make compiler to not delete abstract methods in abstract classes from compiler output.
