### ISSUE TITLE
Injecting Dependencies

### ISSUE THREAD

**Issue by lucasctd** [asvetliakov/Huject#11]
Hi Sr. Svetliakov,

I am not able to inject my dependencies, I am always getting undefined... Idk if I misunderstood something, I am sry if it`s the case, but I can't get it working :v.

The scenario is, I have a class which import the Container, an interface, and concrete class. Thus, I create an instance of container and register my concrete class. However, when I try to call it inside another class, I get null (undefined). I really don't know what's wrong.

You may see how I am doing it through the files below:

[Explorer.ts](https://github.com/lucasctd/metro-explorer/blob/reimplement-in-typescript/src/ts/impl/Explorer.ts):
At the lines 10 and 11 I will import the "interface" and concrete class, respectively.
At the lines 50 and 56 I will create an instance of the container and then register my dependency.

[FileComponent.ts](https://github.com/lucasctd/metro-explorer/blob/reimplement-in-typescript/src/ts/components/FileComponent.ts):
at the line 5 I will import the Inject annotation (decoretor) and at the lines 26 and 27, I will Inject it, but when I check it at the lines 36 and 42, it will show "null".

May you help me with it?

**Comment by asvetliakov** [comment]
Hello Lucas,
The registration is correct, but looks like your ```FileComponent``` isn't being instantiated by container itself. I don't know Vue and don't know how it's instantiating views, but to inject something into class the class must be instantiated either from direct container request: ```Container.resolve``` or through container factory, or be wrapped as some dependency of two previous ways.
I.e, given some chain:
```A -> B -> C``` where C is dependency of B and B is dependency of A:

```Container.resolve(A)``` -> will wrap & instantiate A, B, C
```const a = new A();``` -> won't instantiate B and C

If your ```FileComponent``` is being instantiated somehow by Vue directly via ```new()``` you won't get your dependencies injected into this class.

To workaround this case you can either hook Vue internals (if it's possible) or write some class decorator which wraps constructor and create your class from container:

```ts
export function InstantiateViaContainer(): ClassDecorator {
  return function (target: Function): any {
    // intercept new() with ES6 proxies and return instance from container
    return new Proxy(target, {
      construct: function (target) { return Container.resolve(target, FactoryMethod.OBJECT); }
    }
  }
}

@InstantiateViaContainer()
class FileComponent { ... }
```

Of course you'll need globally available Container for this case, just create & export it in separate file.


Also i wouldn't do any DI for your case, may be a better way is to use view composition/view properties for this.

**Comment by lucasctd** [comment]
Hi @asvetliakov, thx for the quick reply.

What I did to work around this was:

Created a file called huject.config.ts and added the following code:

`import {Container} from 'huject';`

`import {Draggable as DraggableInterface} from './interfaces/Draggable';`
`import Draggable from './impl/Draggable';`

`import Upload from './impl/Upload';`
`import UploadInterface from './interfaces/Upload';`

`const container = new Container();`
`container.register(UploadInterface, Upload);`
`container.register(DraggableInterface, Draggable);`

`export {container};`

and then, imported it in my component and used `this.draggable = container.resolve(Draggable);` to resolve it there.
Now it works. Do you think it's fine?
