### ISSUE TITLE
parameter overlaying combined with injection does not seem to work

### ISSUE THREAD

**Issue by fuzing** [asvetliakov/Huject#2]
Example 1 - This works:
https://gist.github.com/fuzing/9e8ec158a16a3f4b4482

Then see the comments marked with 'NOTE' to see how example 2 differs (there's a parameter in the constructor prior to the @ConstructorInject).
Example 2 - This doesn't:
https://gist.github.com/fuzing/b74cb9e4dbc2ce99775c

Setup code for each Example:
https://gist.github.com/fuzing/5c76bc2767060e5765dc

**Comment by asvetliakov** [comment]
https://github.com/asvetliakov/Huject/blob/master/Readme.md#decorators
See **important** notice.

If you're using constructor injection do not use ordinary constructor params. Such params are assuming that you're trying to instantiate instance via new() so it's loosing all DI benefits anyway.

It's impossible from library side to tell if the constructor param is for injection or not without loosing simplifity (in this case need to prefix with decorator before each argument).

**Comment by fuzing** [comment]
Sorry - I didn't see that.   I apologize.

**Comment by fuzing** [comment]
Alexey:

Unfortunately I do have a use case for combined injected alongside
non-injected parameters (it relates to using 3rd party code, and the fact
that I’m only using huject for service location [i.e. a logger
implementation]).

Thanks for being so helpful thus far.     I don’t expect you to contaminate
your codebase, so I’ll whip up my own simple decorator based injection
scheme that overlays the injected and non-injected parameters and call it
good.

Cheers, and be well,

Peter B.

**Comment by asvetliakov** [comment]
You can try to wrap your dependency into factory or use ContainerFactoryInterface (both are supporting passing non-injected dynamic constructor arguments). Or use any class with injected params as wrapper.
if you're trying to do something like from your gists - you can use property injection for your LoggerInterface and register necessary constructor arguments for this class)
I can hint you more if you provide your use case

**Comment by fuzing** [comment]
Alexey:

Thanks for your assistance -

I went with the “register constructor arguments” option and now have them
all being injected - this seems like the most expedient solution for now
(not elegant but it works).

Thanks and have a great day,

Peter B.
